server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 20GB
      max-request-size: 20GB
  connection-timeout: 300000  # 5 minutes for large file uploads
  max-http-header-size: 64KB

spring:
  application:
    name: file-hosting-app
  
  datasource:
    url: jdbc:h2:file:./data/filehosting
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
        thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  
  # Additional configuration for large file handling
  http:
    multipart:
      enabled: true
      file-size-threshold: 10MB  # Files larger than this will be written to disk
      location: ${java.io.tmpdir}  # Temporary file location

# Custom application properties
app:
  upload:
    path: ${UPLOAD_PATH:./uploads}
    max-size-gb: ${MAX_STORAGE_GB:50}  # Increased to accommodate large video files
  
logging:
  level:
    com.filehosting: DEBUG
    org.springframework.web.multipart: DEBUG
